name: ecommerce
description: "An e-commerce flutter app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider_plus: ^7.0.1
  cupertino_icons:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  colornames: ^0.1.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  readmore: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.8
  dartz: ^0.10.1
  get_it: ^7.7.0
  injectable: ^2.4.4
  retrofit: ^4.9.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  badges: ^3.1.2
  webview_flutter: ^4.13.0
  

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.2
  retrofit_generator: ^10.0.6
  json_serializable: ^6.11.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-.ttf
         